name: "conventional-release-action"
description: "A GitHub Action to automatically tag and create releases based on conventional commits."
outputs:
    tag:
        description: "The tag name of the release."
runs:
    using: node20
    main: "build/index.js"
inputs:
    before:
        description: "The starting commit."
        required: false
        default: ${{ github.event.before }}
    after:
        description: "The ending commit."
        required: false
        default: ${{ github.event.after }}
