name: Build

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: ./
              with:
                  commit-message-format: "release: v%s [skip ci]"
                  git-gpg-key: ${{ secrets.GPG_PRIVATE_KEY }}
