name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Automatic versioning
        id: automatic_versioning
        uses: ./
        with:
          commit-message-format: "release: v%s [skip ci]"
          git-gpg-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Create release
        if: ${{ steps.automatic_versioning.outputs.tag != '' }}
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.automatic_versioning.outputs.tag }}
          body: ${{ steps.automatic_versioning.outputs.release_notes }}
